#!/bin/bash

# We use REALPATH to allow symbolic links to this script, so that the true basedir is found
REALPATH=$(realpath $0)
BASEDIR="$(dirname "$REALPATH")"
echo "Base dir for myND: $BASEDIR"

CMD="java -Xmx4g -cp $BASEDIR/target/mynd-1.0-SNAPSHOT.jar mynd.MyNDPlanner -translatorPath $BASEDIR/ $@"

# report command to execute
echo $CMD
echo

# execute!
$CMD